name: Build and Push Docker Image
on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

env:
  DOCKER_REPO: ghcr.io/healthstudyclub/mailhog-docker

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up QEMU (for emulating other architectures)
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      # Set up Buildx with docker-container driver by default
      - uses: docker/setup-buildx-action@v3
        with:
          install: true

      # Log in to GHCR
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push multi-platform image
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:${{ github.ref_name }}
            ${{ env.DOCKER_REPO }}:latest
